CREATE TABLE "DASH13540"."POC_ResultNOLEARNING" (
		"Case ID" INTEGER,
		"Assurance Number" SYSIBM.DECFLOAT,
		"M anagement Team" VARCHAR(30),
		"Status" VARCHAR(24),
		"Case Channel Type" VARCHAR(14),
		"Case Creation Date" DATE,
		"Case Duration" SMALLINT,
		"Case Resolution Date" TIMESTAMP,
		"Resolution Team" VARCHAR(30),
		"Owner User ID" VARCHAR(12),
		"Case Company" VARCHAR(14),
		"Case Product" VARCHAR(30),
		"Case Product feature" VARCHAR(38),
		"Case Cause" VARCHAR(33),
		"Case Cause Detail A" VARCHAR(56),
		"Case Cause Detail B" VARCHAR(10),
		"Client Channel  Type" VARCHAR(15),
		"Client First Name" VARCHAR(30),
		"Client Last Name" VARCHAR(36),
		"Client Phone" VARCHAR(5),
		"Client Fiscal ID" VARCHAR(17),
		"Clien VAT" BIGINT,
		"Client Address" VARCHAR(5),
		"Client State" VARCHAR(5),
		"Client Contact Zip Code" INTEGER,
		"Client Living Province" VARCHAR(5),
		"Client Living Zip Code" VARCHAR(5),
		"Note for answer to client" VARCHAR(3499),
		"CLIENT_PROVINCE" VARCHAR(28),
		"CLIENT_REGION" VARCHAR(21),
		"PrimaKeyword" VARCHAR(50),
		"SecondaKeyword" VARCHAR(50),
		"TerzaKeyword" VARCHAR(50),
		"RelevancePrimaKeyword" FLOAT,
		"RelevanceSecondaKeyword" FLOAT,		
		"RelevanceTerzaKeyword" FLOAT,
		"PrimaCategory" VARCHAR(50),
		"SecondaCategory" VARCHAR(50),
	    "TerzaCategory" VARCHAR(50),
	    "RelevancePrimaCategory" FLOAT,
	    "RelevanceSecondaCategory" FLOAT,	    
	    "RelevanceTerzaaCategory" FLOAT,	
	    "DocumentSentiment" FLOAT,
	    "MillisecElaborazioneWatson" INTEGER
)
	DATA CAPTURE NONE;

